name: navigator_20
description: Navigation 2.0 example.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.2 <3.0.0"
  flutter: '>=2.0.3'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.2
  provider: 6.0.0
  logger: 1.1.0
  modal_bottom_sheet: 2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
